"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

setup(
    name='iTunes sync',
    version='0.0.0',
    app=['main.py'],
    data_files=[],
    options={'py2app': {}},
    setup_requires=['py2app'],
)
